<template>
  <view class="inheritor-page with-bottom-nav"><view class="inheritor-safe-top"></view><view class="inheritor-heading"><view class="heading-ornament heading-ornament--left">⌁</view><text>非遗传承人</text><view class="heading-ornament heading-ornament--right">⌁</view></view><scroll-view scroll-x class="inheritor-filters"><view v-for="item in filters" :key="item" class="inheritor-filter" :class="{ 'inheritor-filter--active': selectedFilter === item }" @click="selectedFilter = item">{{ item }}</view></scroll-view><view v-if="loading" class="inheritor-state inheritor-state--loading"><content-state type="loading" message="正在加载传承人内容…" /></view><view v-else-if="error" class="inheritor-state"><content-state type="error" :message="error" :retrying="loading" @retry="loadData" /></view><template v-else><view class="inheritor-hero"><image class="inheritor-hero__image" :src="heroImage" mode="aspectFill"></image><view class="inheritor-hero__shade"></view><view class="inheritor-hero__copy"><text class="inheritor-hero__eyebrow">传承人</text><text class="inheritor-hero__title">{{ featuredName }}</text><text class="inheritor-hero__subtitle">国家级非遗项目传承人</text><view class="inheritor-hero__tags"><text>非遗传承人</text><text>非遗项目</text><text>传统技艺</text></view></view><image class="inheritor-hero__figure" :src="mascotImage" mode="aspectFit"></image></view><view class="inheritor-feature-grid"><view v-for="item in featureItems" :key="item.title" class="inheritor-feature" @click="handleUnavailable(item.title)"><text class="inheritor-feature__title">{{ item.title }}</text><text class="inheritor-feature__note">{{ item.note }}</text></view></view><view class="inheritor-section-head"><view><text class="inheritor-section-head__title">代表作品</text><text class="inheritor-section-head__note">传承人创作的非遗好物</text></view><text class="inheritor-section-head__more" @click="goShop">更多 →</text></view><view v-if="products.length" class="inheritor-products"><view v-for="item in products.slice(0, 6)" :key="item.id" class="inheritor-product" @click="goProduct(item.id)"><image class="inheritor-product__image" :src="normalizeImage(item.cover, '/static/mall-demo/placeholder.png')" mode="aspectFill"></image><view class="inheritor-product__body"><text class="inheritor-product__name">{{ item.name }}</text><text class="inheritor-product__meta">{{ item.category || '传统技艺' }}</text><text class="inheritor-product__price">¥{{ formatPrice(item.price) }}</text></view></view></view><content-state v-else type="empty" message="暂无代表作品" /><view class="inheritor-story"><image class="inheritor-story__image" :src="storyImage" mode="aspectFill"></image><view class="inheritor-story__copy"><text class="inheritor-story__eyebrow">传承人的故事</text><text class="inheritor-story__title">一双手，守住一门技艺</text><text class="inheritor-story__note">从师承、作品到体验，走近非遗传承人的日常。</text></view></view></template><bottom-nav current="inheritor" /></view>
</template>

<script>
import BottomNav from '@/components/bottom-nav.vue'
import ContentState from '@/components/content-state.vue'
import { getHome } from '@/common/request/api.js'
import { formatPrice, normalizeImage } from '@/common/utils.js'
export default {
  components: { BottomNav, ContentState },
  data() { return { loading: false, error: '', inheritors: [], products: [], selectedFilter: '全部', heroImage: '/static/home/home-hero.jpg', mascotImage: '/static/home/bronze-beast.png', storyImage: '/static/home/feature-side-bg.png', filters: ['全部', '非遗传承人', '地区', '分类'], featureItems: [{ title: '师承背景', note: '国家级非遗项目传承人' }, { title: '代表作品', note: '查看非遗创作与作品' }, { title: '入驻平台', note: '了解合作与展示方式' }, { title: '可预约体验', note: '预约传承课程与活动' }] } },
  computed: { featuredName() { return this.inheritors[0] && (this.inheritors[0].displayName || this.inheritors[0].name) || '守艺人的日常' } },
  onLoad() { this.loadData() },
  methods: { formatPrice, normalizeImage, async loadData() { this.loading = true; this.error = ''; try { const data = await getHome({}); this.inheritors = Array.isArray(data && data.inheritors) ? data.inheritors : []; this.products = Array.isArray(data && data.products) ? data.products : [] } catch (error) { this.error = error && error.message ? error.message : '传承人内容加载失败，请稍后重试' } finally { this.loading = false } }, goProduct(id) { uni.navigateTo({ url: `/pages/shop/detail?id=${id}` }) }, goShop() { uni.switchTab({ url: '/pages/shop/list' }) }, handleUnavailable(name) { uni.showToast({ title: `${name}功能即将开放`, icon: 'none' }) } }
}
</script>

<style lang="scss" src="./index-recovered.scss" scoped></style>
