-- ============================================================
-- inherit 模块单元测试建表 SQL（H2 MODE=MYSQL）
-- 与 mysql/ruoyi-vue-pro-inherit.sql 的 5 张业务表一一对应
-- ============================================================

-- 1. 传承人表
CREATE TABLE IF NOT EXISTS "inherit_inheritor"
(
    "id"             bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"           varchar(64)  NOT NULL,
    "pinyin"         varchar(128) NULL,
    "avatar"         varchar(512) NULL,
    "cover"          varchar(512) NULL,
    "gender"         int          NOT NULL DEFAULT 0,
    "phone"          varchar(20)  NULL,
    "id_card"        varchar(18)  NULL,
    "level"          varchar(64)  NULL,
    "province_code"  int          NULL,
    "city_code"      int          NULL,
    "district_code"  int          NULL,
    "introduction"   varchar(500) NULL,
    "profile"        text         NULL,
    "specialty"      varchar(255) NULL,
    "experience"     text         NULL,
    "audit_status"   tinyint      NOT NULL DEFAULT 0,
    "audit_remark"   varchar(255) NULL,
    "audit_time"     datetime     NULL,
    "display_status" tinyint      NOT NULL DEFAULT 0,
    "published_at"   datetime     NULL,
    "is_recommend"   int          NOT NULL DEFAULT 0,
    "recommend_sort" int          NOT NULL DEFAULT 0,
    "sort"           int          NOT NULL DEFAULT 0,
    "status"         tinyint      NOT NULL DEFAULT 0,
    "creator"        varchar(64)  NULL     DEFAULT '',
    "create_time"    datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"        varchar(64)  NULL     DEFAULT '',
    "update_time"    datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted"        bit(1)       NOT NULL DEFAULT '0',
    "tenant_id"      bigint       NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '传承人表';

-- 2. 传承人荣誉/资质表
CREATE TABLE IF NOT EXISTS "inherit_inheritor_qualification"
(
    "id"             bigint        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "inheritor_id"   bigint        NOT NULL,
    "type"           varchar(32)   NOT NULL,
    "name"           varchar(128)  NOT NULL,
    "level"          varchar(64)   NULL,
    "issuer"         varchar(128)  NULL,
    "issue_date"     date          NULL,
    "certificate_no" varchar(64)   NULL,
    "description"    varchar(500)  NULL,
    "image_url"      varchar(512)  NULL,
    "sort"           int           NOT NULL DEFAULT 0,
    "status"         tinyint       NOT NULL DEFAULT 0,
    "creator"        varchar(64)   NULL     DEFAULT '',
    "create_time"    datetime      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"        varchar(64)   NULL     DEFAULT '',
    "update_time"    datetime      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted"        bit(1)        NOT NULL DEFAULT '0',
    "tenant_id"      bigint        NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '传承人荣誉/资质表';

-- 3. 传承人作品表（images 存 JSON 字符串，配合 JacksonTypeHandler）
CREATE TABLE IF NOT EXISTS "inherit_inheritor_work"
(
    "id"           bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "inheritor_id" bigint       NOT NULL,
    "name"         varchar(128) NOT NULL,
    "cover"        varchar(512) NULL,
    "images"       varchar(2000) NULL,
    "description"  varchar(1000) NULL,
    "year"         varchar(32)  NULL,
    "material"     varchar(64)  NULL,
    "technique"    varchar(128) NULL,
    "sort"         int          NOT NULL DEFAULT 0,
    "status"       tinyint      NOT NULL DEFAULT 0,
    "creator"      varchar(64)  NULL     DEFAULT '',
    "create_time"  datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"      varchar(64)  NULL     DEFAULT '',
    "update_time"  datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted"      bit(1)       NOT NULL DEFAULT '0',
    "tenant_id"    bigint       NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '传承人作品表';

-- 4. 传承人-非遗项目 关系表
CREATE TABLE IF NOT EXISTS "inherit_inheritor_project_relation"
(
    "id"           bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "inheritor_id" bigint  NOT NULL,
    "project_id"   bigint  NOT NULL,
    "is_primary"   bit(1)  NOT NULL DEFAULT '0',
    "sort"         int     NOT NULL DEFAULT 0,
    "creator"      varchar(64) NULL DEFAULT '',
    "create_time"  datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"      varchar(64) NULL DEFAULT '',
    "update_time"  datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted"      bit(1)   NOT NULL DEFAULT '0',
    "tenant_id"    bigint   NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '传承人-非遗项目 关系表';

-- 5. 传承人关注表
CREATE TABLE IF NOT EXISTS "inherit_inheritor_follow"
(
    "id"           bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id"      bigint  NOT NULL,
    "inheritor_id" bigint  NOT NULL,
    "creator"      varchar(64) NULL DEFAULT '',
    "create_time"  datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"      varchar(64) NULL DEFAULT '',
    "update_time"  datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted"      bit(1)   NOT NULL DEFAULT '0',
    "tenant_id"    bigint   NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '传承人关注表';
