package cn.iocoder.yudao.module.heritage.dal.mysql;
import cn.iocoder.yudao.framework.mybatis.core.mapper.BaseMapperX; import cn.iocoder.yudao.module.heritage.dal.dataobject.ProductSystemSpuDO; import cn.iocoder.yudao.module.heritage.service.ProductItemRow; import org.apache.ibatis.annotations.*; import java.util.List;
@Mapper public interface ProductSystemSpuMapper extends BaseMapperX<ProductSystemSpuDO> {
 @Select("SELECT r.id AS relationId,r.spu_id AS targetId,p.name AS title,p.introduction AS summary,p.pic_url AS coverUrl,p.price AS price,r.sort AS sortOrder FROM heritage_product_system_spu r JOIN product_spu p ON p.id=r.spu_id AND p.deleted=0 AND p.status=1 WHERE r.product_system_id=#{systemId} AND r.status=1 AND r.deleted=0 ORDER BY r.sort ASC,r.id ASC LIMIT #{offset},#{limit}") List<ProductItemRow> selectVisible(Long systemId,long offset,int limit);
 @Select("SELECT COUNT(1) FROM heritage_product_system_spu r JOIN product_spu p ON p.id=r.spu_id AND p.deleted=0 AND p.status=1 WHERE r.product_system_id=#{systemId} AND r.status=1 AND r.deleted=0") long countVisible(Long systemId);
 @Select("SELECT r.id AS relationId,r.spu_id AS targetId,p.name AS title,p.introduction AS summary,p.pic_url AS coverUrl,p.price AS price,r.sort AS sortOrder FROM heritage_product_system_spu r JOIN product_spu p ON p.id=r.spu_id AND p.deleted=0 AND p.status=1 WHERE r.product_system_id=#{systemId} AND r.status=1 AND r.deleted=0 AND (p.name LIKE CONCAT('%',#{keyword},'%') OR p.introduction LIKE CONCAT('%',#{keyword},'%')) ORDER BY r.sort ASC,r.id ASC LIMIT #{offset},#{limit}") List<ProductItemRow> selectVisibleKeyword(Long systemId,String keyword,long offset,int limit);
 @Select("SELECT COUNT(1) FROM heritage_product_system_spu r JOIN product_spu p ON p.id=r.spu_id AND p.deleted=0 AND p.status=1 WHERE r.product_system_id=#{systemId} AND r.status=1 AND r.deleted=0 AND (p.name LIKE CONCAT('%',#{keyword},'%') OR p.introduction LIKE CONCAT('%',#{keyword},'%'))") long countVisibleKeyword(Long systemId,String keyword);
 @Select("SELECT COUNT(1) FROM product_spu WHERE id=#{spuId} AND deleted=0") int countSpu(Long spuId);
}
